### ISSUE TITLE
Rotate Array

### ISSUE THREAD

**Issue by ritesh-dt** [dscvitpune/dsc-hacktoberfest-2021#1]
**Title**: Rotate Array

Given an array, rotate the array to the right by k steps, where k is non-negative.

[Link to coding problem](    https://leetcode.com/problems/rotate-array/    )

**Example 1**
```
Input: nums = [1,2,3,4,5,6,7], k = 3
Output: [5,6,7,1,2,3,4]
Explanation:
rotate 1 steps to the right: [7,1,2,3,4,5,6]
rotate 2 steps to the right: [6,7,1,2,3,4,5]
rotate 3 steps to the right: [5,6,7,1,2,3,4]
````

**Example 2**
```
Input: nums = [-1,-100,3,99], k = 2
Output: [3,99,-1,-100]
Explanation: 
rotate 1 steps to the right: [99,-1,-100,3]
rotate 2 steps to the right: [3,99,-1,-100]
````

**Comment by snehashukkla** [comment]
@ritesh-dt please assign it to me in C++

**Comment by ritesh-dt** [comment]
Sorry, this is just a demo issue I had created

This won't be worked on
