### ISSUE TITLE
Finding middle element in a linked list

### ISSUE THREAD

**Issue by vkinsane** [dscvitpune/dsc-hacktoberfest-2021#13]
**Title**:  Finding middle element in a linked list
**Language**: Any

Given a singly linked list of N nodes.
The task is to find the middle of the linked list. For example, if the linked list is
1-> 2->3->4->5, then the middle node of the list is 3.
If there are two middle nodes(in case, when N is even), print the second middle element.
For example, if the linked list given is 1->2->3->4->5->6, then the middle node of the list is 4.

[Link to coding problem](https://practice.geeksforgeeks.org/problems/finding-middle-element-in-a-linked-list/1)

**Example 1**
```
Input:
LinkedList: 1->2->3->4->5
Output: 3 
Explanation: 
Middle of linked list is 3.
````
**Example 2**
```
Input:
LinkedList: 2->4->6->7->5->1
Output: 7 
Explanation: 
Middle of linked list is 7.
````

**Comment by ritik2209** [comment]
Please assign it to me

**Comment by AkshayBargaje** [comment]
@vkinsane I would like solve this using C++ , so please assign it to me.

**Comment by TejasGadi** [comment]
@vkinsane I would like to work on this issue. I will use C++ to solve this.                                                                                                   
Could you please assign this to me

**Comment by ritesh-dt** [comment]
@ritik2209 assigned
@AkshayBargaje @TejasGadi you may choose another language to solve this question.

**Comment by AkshayBargaje** [comment]
@vkinsane I can do it with C.

**Comment by shubhamshah14102** [comment]
@vkinsane I would like to work on this issue. I will use Java to solve the assigned issue.

**Comment by shubhamshah14102** [comment]
@vkinsane I would like to work on this issue. I will use Java to solve this.
Could you please assign this to me

**Comment by vkinsane** [comment]
@AkshayBargaje  Assigned.

**Comment by vkinsane** [comment]
@shubhamshah14102  Assigned.

**Comment by AkshayBargaje** [comment]
@vkinsane sorry i mistakenly unassigned myself can you assign me again please

**Comment by vkinsane** [comment]
Done @AkshayBargaje

**Comment by CRAZYGEEKS04** [comment]
@vkinsane i can do this by using python. please assign it to me

**Comment by ritesh-dt** [comment]
@CRAZYGEEKS04 assigned in Python

**Comment by shubhamshah14102** [comment]
do we have to accept the input from the user and then work on it?

**Comment by CRAZYGEEKS04** [comment]
yes

**Comment by shubhamshah14102** [comment]
i am unable to understand the pattern of input accepting .
do i accept it as a string and then seprate it into numbers ("1-->2-->3-->4-->5)
OR
do i accept seprate numbers using the loop as integers?

**Comment by ritik2209** [comment]
I have made a PR and its been merged as well,but the Hacktoberfest website is saying,this repo is excluded from Hacktoberfest
