### ISSUE TITLE
Validate an IP Address

### ISSUE THREAD

**Issue by vkinsane** [dscvitpune/dsc-hacktoberfest-2021#14]
**Title**: Validate an IP Address
**Language**: Any

Write a program to Validate an IPv4 Address. According to Wikipedia, IPv4 addresses are canonically represented in dot-decimal notation, which consists of four decimal numbers, each ranging from 0 to 255, separated by dots, e.g., 172.16.254.1 . The generalized form of an IPv4 address is (0-255).(0-255).(0-255).(0-255). Here we are considering numbers only from 0 to 255 and any additional leading zeroes will be considered invalid.

Your task is  to complete the function isValid which returns 1 if the ip address is valid else returns 0. The function takes a string s as its only argument .

[Link to coding problem](https://practice.geeksforgeeks.org/problems/validate-an-ip-address/1)

**Example 1**
```
Input:
ip = 222.111.111.111
Output: 1
````
**Example 2**
```
Input:
ip = 5555..555
Output: 0
Explanation: 5555..555 is not a valid ip address, as the middle two portions are missing.
````

**Comment by gokhalevedant06** [comment]
Hi, I would like to solve this problem using Python
Can you please assign this to me?

**Comment by ritesh-dt** [comment]
@gokhalevedant06 assigned

**Comment by AMGOcyber123** [comment]
@ritesh-dt  can i do this is in java script if possible !

**Comment by ritesh-dt** [comment]
@AMGOcyber123 assigned

**Comment by royshreyaaa** [comment]
@ritesh-dt Can you please assign this to me? I'll do it using Java.

**Comment by ritesh-dt** [comment]
@royshreyaaa assigned

**Comment by PrathmeshN99** [comment]
@ritesh-dt can you please assign this problem to me? I'll use c++

**Comment by ritesh-dt** [comment]
@PrathmeshN99 assigned for C++

**Comment by AMGOcyber123** [comment]
@ritesh-dt  despite merging my hacktober profile isnt updated can you please look into it ?
