### ISSUE TITLE
Rearrange a linked list

### ISSUE THREAD

**Issue by vkinsane** [dscvitpune/dsc-hacktoberfest-2021#15]
**Title**: Rearrange a linked list
**Language**: Any

Given a singly linked list, the task is to rearrange it in a way that all odd position nodes are together and all even positions node are together.
Assume the first element to be at position 1 followed by second element at position 2 and so on.
Note: You should place all odd positioned nodes first and then the even positioned ones. (considering 1 based indexing). Also, the relative order of odd positioned nodes and even positioned nodes should be maintained.

[Link to coding problem](https://practice.geeksforgeeks.org/problems/rearrange-a-linked-list/1)

**Example 1**
```
Input:
LinkedList: 1->2->3->4
Output: 1 3 2 4 
Explanation: 
Odd elements are 1, 3 and even elements are 
2, 4. Hence, resultant linked list is 
1->3->2->4.
````

**Example 2**
```
Input:
LinkedList: 1->2->3->4->5
Output: 1 3 5 2 4 
Explanation: 
Odd elements are 1, 3, 5 and even elements are
2, 4. Hence, resultant linked list is
â€‹1->3->5->2->4.
````

**Comment by sneha-baser** [comment]
@vkinsane I would like to work on issue using c++, could you please assign me?

**Comment by ritesh-dt** [comment]
@sneha-baser  I've already assigned 'Trapping Rainwater'. So please complete that prior to doing this.

**Comment by TejasGadi** [comment]
@vkinsane I would like to work on this issue. I will use C++ to solve this.
Could you please assign this to me

**Comment by ritesh-dt** [comment]
@TejasGadi assigned
