### ISSUE TITLE
132 Geeky Buildings

### ISSUE THREAD

**Issue by vkinsane** [dscvitpune/dsc-hacktoberfest-2021#16]
**Title**: 132 Geeky Buildings
**Language**: Any

There are N buildings in Linear Land. They appear in a linear line one after the other and their heights are given in the array arr[]. Geek wants to select three buildings in Linear Land and remodel them as recreational spots. The third of the selected building must be taller than the first and shorter than the second.
Can geek build the three-building recreational zone? 

[Link to coding problem](https://practice.geeksforgeeks.org/problems/355f731797ea1acbd5ab698b19eb1c3c469aa837/1/)

**Example 1**
```
Input:
N = 6
arr[] = {4, 7, 11, 5, 13, 2}
Output:
True
Explanation:
[4, 7, 5] fits the condition.
````

**Example 2**
```
Input:
N = 4
arr[] = {11, 11, 12, 9}
Output:
False
Explanation:
No 3 buildings fit the given condition. 
````

**Comment by rbb-99** [comment]
@vkinsane I can provide a solution to this problem using stack operations in the language C++, could you please assign me it?

**Comment by Pavan49719** [comment]
@ritesh-dt Would you assign this to me ? I will use python language to solve this problem.
