### ISSUE TITLE
Anagram

### ISSUE THREAD

**Issue by Komal3006** [dscvitpune/dsc-hacktoberfest-2021#24]
**Title**: < Anagram >
**Language**: C++

<Given two strings a and b consisting of lowercase characters. The task is to check whether two given strings are an anagram of each other or not. An anagram of a string is another string that contains the same characters, only the order of characters can be different. For example, “act” and “tac” are an anagram of each other.>

[Link to coding problem](    <https://practice.geeksforgeeks.org/problems/anagram-1587115620/1>    )

**Example 1**
```
Input:
a = geeksforgeeks, b = forgeeksgeeks
Output: YES
Explanation: Both the string have same
characters with same frequency. So, 
both are anagrams.
````

**Comment by mohitkhedkar** [comment]
I would like to work on this issue

**Comment by Komal3006** [comment]
Please assign this to me.

**Comment by AMGOcyber123** [comment]
@ritesh-dt if assign this to me if possible

**Comment by ritesh-dt** [comment]
Please read CONTRIBUTING.md before creating the pull requests.

**Comment by royshreyaaa** [comment]
@ritesh-dt
Please assign this to me.
