### ISSUE TITLE
Longest Substring Without Repeating Characters

### ISSUE THREAD

**Issue by ritesh-dt** [dscvitpune/dsc-hacktoberfest-2021#3]
**Title**: Longest Substring Without Repeating Characters
**Language**: Any

Given a string `s`, find the length of the longest substring **without repeating** characters.

[Link to coding problem](    https://leetcode.com/problems/longest-substring-without-repeating-characters/    )

**Example 1**
```
Input: s = "abcabcbb"
Output: 3
````

**Example 2**
```
Input: s = "pwwkew"
Output: 3
````

**Comment by AkshayBargaje** [comment]
@ritesh-dt  please assign this to me ,I'll do this using python.

**Comment by ritesh-dt** [comment]
You have already been assigned another issue.

**Comment by sanskrutirajput** [comment]
@ritesh-dt please will you assign me this, l'll do it in python.

**Comment by Pavan49719** [comment]
@ritesh-dt Would you please assign this to me, I will do this in python

**Comment by ritesh-dt** [comment]
@sanskrutirajput assigned

**Comment by ritesh-dt** [comment]
@Pavan49719 Please choose another language or issue

**Comment by Pavan49719** [comment]
> @Pavan49719 Please choose another language or issue

Yeah I will do it in C Lang.

**Comment by ritesh-dt** [comment]
@Pavan49719 assigned for C

**Comment by dev-ameyjoshi** [comment]
Hello !
@ritesh-dt  
Please assign this to me.
Language : Javascript

**Comment by ritesh-dt** [comment]
@dev-ameyjoshi assigned.

**Comment by kulkarni-anurag** [comment]
@ritesh-dt Will you assign me this task, I'll use C++ language.

**Comment by ritesh-dt** [comment]
> @ritesh-dt Will you assign me this task, I'll use C++ language.
@kulkarni-anurag assigned for C++
