### ISSUE TITLE
101. Symmetric Tree

### ISSUE THREAD

**Issue by flick-23** [dscvitpune/dsc-hacktoberfest-2021#31]
**Title**:  Symmetric Tree
**Language**:  Python

Given the root of a binary tree, check whether it is a mirror of itself (i.e., symmetric around its center).

[Link to coding problem](    https://leetcode.com/problems/symmetric-tree/    )

**Example 1**
```
Input: root = [1,2,2,3,4,4,3]
Output: true
````
**Example 2**
```
Input: root = [1,2,2,null,3,null,3]
Output: false
````

**Comment by flick-23** [comment]
I request you to assign me this problem.

**Comment by ritesh-dt** [comment]
Actually, we are only allowing 1 contribution per person. So you can keep this issue open for others to use or close it.

**Comment by rohitamrutkar1204** [comment]
@ritesh-dt Can you assign me this issue. I will provide the solution in C++.

**Comment by ritesh-dt** [comment]
@rohitamrutkar1204 assigned in C++
