### ISSUE TITLE
Is Graph Bipartite?

### ISSUE THREAD

**Issue by sn2606** [dscvitpune/dsc-hacktoberfest-2021#32]
**Title**: Is Graph Bipartite?
**Language**: C++

There is an undirected graph with `n` nodes, where each node is numbered between `0` and `n - 1`. You are given a 2D array graph, where `graph[u]` is an array of nodes that node `u` is adjacent to. More formally, for each `v` in `graph[u]`, there is an undirected edge between node `u` and node `v`. The graph has the following properties:

- There are no self-edges (`graph[u]` does not contain `u`).
- There are no parallel edges (`graph[u]` does not contain duplicate values).
- If `v` is in `graph[u]`, then `u` is in `graph[v]` (the graph is undirected).
- The graph may not be connected, meaning there may be two nodes `u` and `v` such that there is no path between them.

A graph is bipartite if the nodes can be partitioned into two independent sets `A` and `B` such that every edge in the graph connects a node in set `A` and a node in set `B`.

Return `true` _if and only if it is bipartite_.

[Link to coding problem]( https://leetcode.com/problems/is-graph-bipartite/ )

**Example 1**
```
Input: graph = [[1,2,3],[0,2],[0,1,3],[0,2]]
Output: false
````

**Example 2**
```
Input: graph = [[1,3],[0,2],[1,3],[0,2]]
Output: true
````

**Comment by rishikeshreddyakkireddy** [comment]
can I code contribute using java?

**Comment by ritesh-dt** [comment]
@sn2606 assigned for C++
@rishikeshreddyakkireddy  assigned for Java

**Comment by ritesh-dt** [comment]
@sn2606 Please do not close this issue as @rishikeshreddyakkireddy is also an assignee.

**Comment by rishikeshreddyakkireddy** [comment]
Ok i will not close the issue..
