### ISSUE TITLE
Coin Change

### ISSUE THREAD

**Issue by ritesh-dt** [dscvitpune/dsc-hacktoberfest-2021#4]
**Title**: Coin Change
**Language**: Any

You are given an integer array `coins` representing coins of different denominations and an integer amount representing a total amount of money.

Return the fewest number of coins that you need to make up that amount. If that amount of money cannot be made up by any combination of the coins, return `-1`.

You may assume that you have an infinite number of each kind of coin.

[Link to coding problem](    https://leetcode.com/problems/coin-change/    )

**Example 1**
```
Input: coins = [1,2,5], amount = 11
Output: 3
````
**Example 2**
```
Input: coins = [1,2,5], amount = 11
Output: 3
````

**Comment by rbb-99** [comment]
@ritesh-dt I can provide an optimum solution to this Coin change problem using C++ . Could you please assign me it?

**Comment by ritesh-dt** [comment]
@rbb-99 Assigned

**Comment by AdityaJB** [comment]
I would like to solve this problem using Python
Can you please assign this to me?

**Comment by AdityaJB** [comment]
@ritesh-dt  Can you assign this to me. I will do it in python.
