### ISSUE TITLE
Maximum Profit in Job Scheduling

### ISSUE THREAD

**Issue by HIMANSHU3107** [dscvitpune/dsc-hacktoberfest-2021#5]
**Title**: Maximum Profit in Job Scheduling
**Language**: Any

We have n jobs, where every job is scheduled to be done from startTime[i] to endTime[i], obtaining a profit of profit[i].

You're given the startTime, endTime and profit arrays, return the maximum profit you can take such that there are no two jobs in the subset with overlapping time range.

If you choose a job that ends at time X you will be able to start another job that starts at time X.

[Link to coding problem](    https://leetcode.com/problems/maximum-profit-in-job-scheduling/   )

**Example 1**
![image](https://assets.leetcode.com/uploads/2019/10/10/sample1_1584.png)
```
Input: startTime = [1,2,3,3], endTime = [3,4,5,6], profit = [50,10,40,70]
Output: 120
Explanation: The subset chosen is the first and fourth job. 
Time range [1-3]+[3-6] , we get profit of 120 = 50 + 70.
````
**Example 2**
![image](https://assets.leetcode.com/uploads/2019/10/10/sample22_1584.png)
```
Input: startTime = [1,2,3,4,6], endTime = [3,5,10,6,9], profit = [20,20,100,70,60]
Output: 150
Explanation: The subset chosen is the first, fourth and fifth job. 
Profit obtained 150 = 20 + 70 + 60.
````

**Comment by DoyelA** [comment]
@HIMANSHU3107 kindly assign this to me

**Comment by Sourajita21** [comment]
I had solved it and created a pull request .Please merge it sir . If you find any issues then I'm ready to edit the file. Thank you Sir.
