### ISSUE TITLE
First Missing Positive

### ISSUE THREAD

**Issue by ritesh-dt** [dscvitpune/dsc-hacktoberfest-2021#6]
**Title**: First Missing Positive
**Language**: Any

Given an unsorted integer array `nums`, return the smallest missing positive integer.

You must implement an algorithm that runs in `O(n)` time and uses constant extra space.

[Link to coding problem](    https://leetcode.com/problems/first-missing-positive/    )

**Example 1**
```
Input: nums = [1,2,0]
Output: 3
````

**Example 2**
```
Input: nums = [3,4,-1,1]
Output: 2
````

**Comment by Adwait01-Bhosale** [comment]
@ritesh-dt  i want to work on this issue and i would also like to do it in CPP.

Could you please assign this to me.

**Comment by AMGOcyber123** [comment]
@ritesh-dt  so would i , if possible do assign me to it

**Comment by ritesh-dt** [comment]
@Adwait01-Bhosale assigned for C++

**Comment by ritesh-dt** [comment]
@AMGOcyber123 which language are you going to use?

**Comment by The-Sanskar-Jain0901** [comment]
@ritesh-dt  can you please assign this to me . I would this problem in java

**Comment by PrathmeshN99** [comment]
@ritesh-dt can you assign this problem to me? I'll use python

**Comment by ritesh-dt** [comment]
@The-Sanskar-Jain0901 assigned for Java

**Comment by ritesh-dt** [comment]
@PrathmeshN99 Sorry, but you have already been assigned another issue to work on

**Comment by AdityaJB** [comment]
Can you assign this problem to me. I will do it in python.

**Comment by Pavan49719** [comment]
@ritesh-dt Would you assign this task to me. I will do it in python.

**Comment by AdityaJB** [comment]
@ritesh-dt can you assign this problem to me. I'll do it in python
