### ISSUE TITLE
Trapping Rain Water

### ISSUE THREAD

**Issue by ritesh-dt** [dscvitpune/dsc-hacktoberfest-2021#8]
**Title**: Trapping Rain Water
**Language**: Any

Given `n` non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining.

[Link to coding problem](    https://leetcode.com/problems/trapping-rain-water/    )

**Example 1**
![Image of height map stored as array](https://assets.leetcode.com/uploads/2018/10/22/rainwatertrap.png)
```
Input: height = [0,1,0,2,1,0,1,3,2,1,2,1]
Output: 6
````

**Example 2**
```
Input: height = [4,2,0,3,2,5]
Output: 9
````

**Comment by sneha-baser** [comment]
@ritesh-dt  I would like to work on this issue using c++. could you please assign it to me?

**Comment by ritesh-dt** [comment]
@sneha-baser assigned
